### ISSUE TITLE
Cert Struggles

### ISSUE THREAD

**Issue by ppannuto** [um-cseg/chez-betty#163]
I saw something on e-mail with Laura and a new cert -- while you're at it:

![screen shot 2015-01-09 at 1 18 11](https://cloud.githubusercontent.com/assets/339422/5676136/7e88cbda-979d-11e4-9b83-9fbd1c4e4ef4.png)

**Comment by zakird** [comment]
There's nothing we can do about this until a new cert comes around. This is
an InCommon problem.

**Comment by bradjc** [comment]
It seems https doesn't work at all right now
