### ISSUE TITLE
Admin graphs should visually indicate weekends

### ISSUE THREAD

**Issue by ppannuto** [um-cseg/chez-betty#168]
I'm envisioning something like a light shading of weekends

**Comment by ppannuto** [comment]
This is do-able in highcharts:
http://stackoverflow.com/questions/19186249/chart-background-highlight-in-highchart

I couldn't find an easy way to do it in chart.js. We should consider changing these graphs over and dropping chart.js completely.

**Comment by ppannuto** [comment]
Add this gem to the list of indictments against chart.js -- apparently it (or our usage of it) doesn't handle resizing the browser window

![screen shot 2015-02-24 at 11 57 37](https://cloud.githubusercontent.com/assets/339422/6354282/6300754a-bc1c-11e4-8642-11d676f91a65.png)

**Comment by bradjc** [comment]
Eh, doesn't seem to be much interest in this.
