### ISSUE TITLE
Chez-Betty down

### ISSUE THREAD

**Issue by aaspring** [um-cseg/chez-betty#169]
Screen is showing internal database error. Doesn't recognize keyboard input when plugged in and trying to refresh the page. Does recognize mouse (touch-screen) input.

Also IOU for 2 Monsters + 1 Mountain Dew

**Comment by ppannuto** [comment]
Server is up again. The IOU is taken care of:

![capture](https://cloud.githubusercontent.com/assets/339422/6364689/1a0f7d5c-bc78-11e4-8d3c-1e5e61f99688.PNG)
