### ISSUE TITLE
Users logging out without pressing the pay button

### ISSUE THREAD

**Issue by rahmati** [um-cseg/chez-betty#176]
I've seen a couple of cases where users assume the system will charge them for the items they have scanned and there is no need to press the pay button if they simply log out. Two possible solutions for this:
(1) Add a prompt to ask the user if he would like to pay for items in the cart before logging out. 
(2) Save items in the cart for their next transaction.

**Comment by ppannuto** [comment]
I like (1), I think it's an easy fix, probably a more general JS pop-up
that triggers if you try to leave the purchase page with any items in your
"cart".

I think (2) would be harder, I'm adverse to DB changes at this point if it
can be helped, and hopefully (1) will largely solve the problem. We can
revisit this if it's insufficient.

@rahmati, feeling up to hacking on Betty? :)

**Comment by ppannuto** [comment]
I don't think this has been an issue since the Purchase & Logout button was added.
