### ISSUE TITLE
Support Paypal/Google Wallet

### ISSUE THREAD

**Issue by rahmati** [um-cseg/chez-betty#177]
This can be as simple as providing an email for people to transfer money to.

**Comment by ppannuto** [comment]
We just implemented Stripe support to accept credit cards [in testing / not
deployed] -- If you want to add others, Pull Requests Welcome (TM) :D

**Comment by rahmati** [comment]
I can probably take a stab at this (and the log out pop up) if you can direct me to the files I should look at.

**Comment by ppannuto** [comment]
Take a look at the series of commits for issue #39. I should have put them in a branch, I didn't, sorry :/

The logout popup should be easier, that one will probably be a contained change in `templates/purchase.jinja2`. Broadly, there are three contexts floating around, the admin context for administration, the user context for when a user is logged into the browser (e.g. on their laptop), and the service context (the Betty terminal). The first two are labeled, the service context is all the unlabeled stuff (legacy I suppose).

**Comment by rahmati** [comment]
How do we want this to be designed?
Do we want to add Paypal and Google Wallet as two new options in deposit or should we just merge them with cash deposit? Assuming that we want to avoid fees (and thus use the honor system similar to cash deposit); all we need to do is to provide an email address for people to transfer money to along with some instructions on how to avoid the fees. 

The plus side of merging this with cash is that it requires minimal effort to implement, the negative side is that there won't be a way to distinguish the 3 deposit types from one another. It is also obviously less clean.

If we want to implement them as two new buttons, how should they be arranged in the deposit page? Should they go in a new row?

**Comment by ppannuto** [comment]
On Fri, Apr 10, 2015 at 2:12 AM, Amir Rahmati <notifications@github.com>
wrote:

> How do we want this to be designed?
> Do we want to add Paypal and Google Wallet as two new options in deposit
> or should we just merge them with cash deposit?
>
I think it'd be nice to keep them split out as their own entities. It's
useful to track what features are actually used.

> Assuming that we want to avoid fees (and thus use the honor system similar
> to cash deposit); all we need to do is to provide an email address for
> people to transfer money to along with some instructions on how to avoid
> the fees.
>
I'm a little wary of fee avoidance. I'd rather not run afoul of the ToS for
these providers. For CC processing, we just pass the fees directly onto the
user, e.g. for a $20 deposit, we charge their card (20*1.029 + 0.30) =
20.88

>  The plus side of merging this with cash is that it requires minimal
> effort to implement, the negative side is that there won't be a way to
> distinguish the 3 deposit types from one another. It is also obviously less
> clean.
>
> If we want to implement them as two new buttons, how should they be
> arranged in the deposit page? Should they go in a new row?
>
I don't think the terminal is the best place for these kind of deposits. I
think the user homepage makes more sense. See the credit card
implementation for an example.

**Comment by bradjc** [comment]
We can re-open if needed.
