### ISSUE TITLE
Izze box had new items

### ISSUE THREAD

**Issue by brghena** [um-cseg/chez-betty#188]
Izze Sparkling Cherry Lime is in the box, but wasn't in the system. I added the item, but you should fix the box at some point.

**Comment by ppannuto** [comment]
Aren't you a manager / can't you fix this?

**Comment by brghena** [comment]
I think I didn't have the receipt or something? Maybe I was unsure what was actually in a box because they were already placed in the fridge. Yeah, I'm going with that one.
