### ISSUE TITLE
We should probably stop saying "PR Welcome." without testing that the site works with dev.ini.example

### ISSUE THREAD

**Issue by bradjc** [um-cseg/chez-betty#202]
Our in-house .ini file has gotten pretty complicated.

**Comment by ppannuto** [comment]
I just tested this from a clean install. There was a small bug in initialize_db, which I fixed, but otherwise it works just fine out of the box.

**Comment by ppannuto** [comment]
I thought you meant there were missing keys or something. All of the authentication keys are obviously placeholders. You're right that we do need to do something about ldap. We could either circumvent ldap login for development, or instantiate one of the many fake ldap severs that people seem to have written:

https://pypi.python.org/pypi/fakeldap/0.5.1
https://github.com/per-garden/fakeldap

I lean slightly towards the latter, but then we have to populate it with fake data that looks like the kind of data we expect, which is a bit of work.

**Comment by bradjc** [comment]
I added some more to readme.md
