### ISSUE TITLE
"Pay and Logout" doesn't log out

### ISSUE THREAD

**Issue by aaspring** [um-cseg/chez-betty#213]
If you owe Betty money, when you click "Pay and Logout" (or something like that) from the purchase screen, it sends you to the deposit screen and *NOT* the home screen. This is a major UX problem b/c users get in the habit of touching the big, yellow button at the top of the screen and walking away. The the system later decides that it should work differently and leaves their account logged in.

**Comment by ppannuto** [comment]
It changes from Pay and Logout to Pay and Deposit if you owe too much
money. Think the cutoff is either $5 or $20, don't recall which.

**Comment by aaspring** [comment]
$5, yeah, but it breaks user muscle-memory which is my bigger concern, people leaving their accounts logged-in b/c the button changed text. The delay between pressing the button and it changing display makes it worse b/c users have the opportunity to walk away before they see that it's at the Deposit screen and not the Log-in screen.

**Comment by ppannuto** [comment]
Yeah.. Pretty much zero sympathy for the plight of people in debt. Worst
case IMO it's a training function that further causes people to pay
attention to their balance.
