### ISSUE TITLE
Move request item to user page

### ISSUE THREAD

**Issue by ppannuto** [um-cseg/chez-betty#220]
Gets it off of the terminal screen where people may be tempted to click it. Also gives us a way to track who submitted requests.

**Comment by bradjc** [comment]
We reallyyyyyyyyyyyyy need to decide on a way to detect terminal vs not. Maybe just is `Betty` logged in?

**Comment by ppannuto** [comment]
That could probably be sufficient. Maybe the right thing to do is have the
/ page be a banner with "admin" "user" and "terminal" buttons and the
terminal home live at /terminal

**Comment by bradjc** [comment]
But then it's not friendly for people who go to chezbetty.eecs.umich.edu on their own computer.

**Comment by ppannuto** [comment]
I think this goes in hand with the other comment of expecting site users to
basically always be logged in.

It would also let us do things like disable requesting items if you have a
negative balance.
