### ISSUE TITLE
Need a way to close accounts

### ISSUE THREAD

**Issue by bradjc** [um-cseg/chez-betty#230]
Probably good to have a way to mark which users have moved on and aren't likely to use Betty again. This would keep the user list from growing forever and a way to settle small amounts of debt (i.e. I think we can forgo getting 16 cents from somebody).

**Comment by ppannuto** [comment]
I would like if this wasn't the same as disabling them -- if people come
back to visit (recruiting trips, etc), Betty should still work for them.
