### ISSUE TITLE
Cannot get to credit card payback page.

### ISSUE THREAD

**Issue by tyler-markvluwer** [um-cseg/chez-betty#231]
Hello. I was hoping to pay back my chez betty debt by going to https://chezbetty.eecs.umich.edu/tylermar

It simply redirects me back to the wall of shame page. I tried it with other usernames and browsers and it seems to be true for all. It's taunting me by showing me my debt and not letting me pay ;)

**Comment by ppannuto** [comment]
Try https://chezbetty.eecs.umich.edu/user or
https://chezbetty.eecs.umich.edu/paydebt/tylermar

There's no page at /uniqname
