### ISSUE TITLE
De Liege Wafel not listed 

### ISSUE THREAD

**Issue by alexandertmills** [um-cseg/chez-betty#256]
De Liege Wafels from Boxed.com no longer ship with barcodes on the individual wrappers. There is presently no "Items w/o Barcode" entry for these Belgian goodies. There is a barcode on the retail box, but that is also not in the system. 

I really want one of these waffles.

**Comment by ppannuto** [comment]
Ugh. Can fix. In the short term you should be able to scan the box and that
will add a waffle.

**Comment by alexandertmills** [comment]
I tried, but the barcode on the box is not listed. Perhaps they changed that also? I know Boxed was trying to get rid of their old stock for a while, probably related to these changes.

I took a waffle. This issue is my IOU to Ms. Betty.
