### ISSUE TITLE
Don't show disabled items when searching items during a restock

### ISSUE THREAD

**Issue by ppannuto** [um-cseg/chez-betty#257]

**Comment by bradjc** [comment]
Then how would we ever restock those items?

**Comment by ppannuto** [comment]
Enable them first?

  

Or at least separate them out to a separate view / list

On Apr 3 2016, at 12:11 pm, Brad Campbell &lt;notifications@github.com&gt;
wrote:  

> Then how would we ever restock those items?  
  
On Sat, Apr 2, 2016, 3:44 PM Pat Pannuto &lt;notifications@github.com&gt;
wrote:  
  
&gt; —  
&gt; You are receiving this because you are subscribed to this thread.  
&gt; Reply to this email directly or view it on GitHub  
&gt; &lt;https://github.com/um-cseg/chez-betty/issues/257&gt;  
&gt;  

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/um-cseg
/chez-betty/issues/257#issuecomment-205004355)![](https://github.com/notificat
ions/beacon/AAUt3q4eNfaprZkk-SfBoqKH5w3f0xNcks5pz-bJgaJpZM4H-XIu.gif)
