### ISSUE TITLE
Add support for Physical Web

### ISSUE THREAD

**Issue by dadrian** [um-cseg/chez-betty#265]
Websites are near you. Chez Betty is near you.

https://google.github.io/physical-web/

**Comment by bradjc** [comment]
There are actually many (almost) supported physical web things in the lounge.

Tell google to implement web bluetooth on chrome.

**Comment by dadrian** [comment]
https://bugs.chromium.org/p/chromium/issues/list?can=2&q=web+component%3ABlink%3EBluetooth+&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids
