### ISSUE TITLE
figure out hangs :/

### ISSUE THREAD

**Issue by ppannuto** [um-cseg/chez-betty#290]
The "Purchase" / "Purchase & Logout" button sometimes seems to not work.. which then requires a keyboard F5 refresh to get things going again. We should see if there isn't some way to detect this / deal with this client-side (i.e. if purchase button bush does not have response in 10s do something else)

**Comment by brghena** [comment]
To prod at this one, I saw some unintentional Betty theft today.

Person A scanned several dollars of items, clicked `Purchase and Logout` and left. Screen hangs on purchasing.

Person B tries clicking buttons to no avail. Person B tries swiping his card. The terminal immediately moves to his account. He goes "Oh, great!" and scans items to be purchased and clicks `Purchase and Logout`. Screen hangs on purchasing again.

I note his dollar amount and ask him to do an experiment. I swipe my card, going to my account, then he swipes his card going to his account. His dollar amount is the original value, _no purchase was made_. We additionally confirmed that the purchase was not erroneously placed on my account.

Just clicking "Logout" (having scanned no items) seemed to allow us to log out and back to the home screen at which point everything was working again and we both purchased items normally.

**Comment by ppannuto** [comment]
I'm not sure what's causing the hangs, but part of what was slowing down the terminal screen loading was pulling down the wall of shame info on every load of the login screen. I added an index to `events.timestamp`, which brought the page load time down from ~3s to ~300ms on my debug environment (and makes the live feel much snappier).

Hopefully this will at least help avert whatever race we're hitting here until we have time to track it down.

**Comment by bradjc** [comment]
It's amazing that any large web apps work at any time.
