### ISSUE TITLE
Can't install development environment -- getVersion() error

### ISSUE THREAD

**Issue by alexandertmills** [um-cseg/chez-betty#291]
I'm following the instructions on the README to get the dev environment set up. However, when I try to run $ pip install -e ./, Python complains that it can't find a version number. I tried this in a Python3 interpreter (import version, version.getVersion()) and was met with the same error.

Any suggestions one what might be wrong and how I might correct it?

Gist of what I tried [here](https://gist.github.com/alexandertmills/08f18cc19335ac5075da5195dd29578b)

Thanks,

**Comment by bradjc** [comment]
Seems to fail if you install not in a git repo. Git cloning will fix this temporarily.

**Comment by alexandertmills** [comment]
I was -- git cloned the chez-betty repo. …should I be doing something else?

**Comment by bradjc** [comment]
I've got it working when I `git clone` and I get the error you have when I download the `.zip` file.

**Comment by alexandertmills** [comment]
Interesting. I definitely cloned it. Whatever.
