### ISSUE TITLE
Clicking "Pay Custom Amount" on the user page with invalid input results in exception

### ISSUE THREAD

**Issue by anrddh** [um-cseg/chez-betty#302]
The user should probably just see a flash message indicating they entered invalid input instead of this "big scary error":

![screen shot 2017-02-03 at 19 40 48](https://cloud.githubusercontent.com/assets/5279150/22613715/ae9eba32-ea48-11e6-995f-60c3471b4000.png)

This happens if you click "Pay Custom Amount" when the input textbox is empty or has a non-numerical string in it.

**Comment by bradjc** [comment]
I think I actually fixed this recently.
