### ISSUE TITLE
[BUG][Solved] Uniqname is case-sensitive

### ISSUE THREAD

**Issue by BGR360** [um-cseg/chez-betty#308]
Fixed by PR #309 

Real Kerberos login is case-insensitive on the uniqname. This can make it confusing for users (e.g. me today) when they try to login to their Chez Betty account with a capitalized uniqname (e.g. 'Bgreeves' instead of 'bgreeves') and the login fails. On mobile browsers, login fields often capitalize the first letter by default.

**Comment by ppannuto** [comment]
Fixed by #309
