### ISSUE TITLE
Add error that accounts must be created at the terminal

### ISSUE THREAD

**Issue by shreve** [um-cseg/chez-betty#320]
When I try to create an account using the Forgot Password form, I get "Bad uniqname or umid"

I performed an LDAP search using my credentials to confirm I was entering my exact case-correct uniquename and I am. However, I don't have access to `entityid` so I can't confirm my UMID is correctly matching.

**Comment by AykeriZero** [comment]
I had the same issue, but I think you have to go to Chez Betty first and scan your mcard. It creates an account for you, then you can use the form to get a password.

**Comment by ppannuto** [comment]
Correct. Account creation requires physical presence at the Betty terminal.
I’ll leave this issue open though as we could probably update the text on
the site to make this a bit more clear

**Comment by shreve** [comment]
Ok, thank you.
