### ISSUE TITLE
API for building on top of CB accounts

### ISSUE THREAD

**Issue by bradjc** [um-cseg/chez-betty#71]
So since we have this nice account system for um students we should be able to run other applications on top of peoples accounts. Examples: weekly happy hour with entrance fee that you can pay with your CB account, coffee club with monthly debits, etc

Basically we make betty a bank.

**Comment by dadrian** [comment]
An honor-system bank?

![nope](http://i.imgur.com/ffgtvJG.gif)

**Comment by bradjc** [comment]
This would be so cool, probably not feasible post making an actual company.
