### ISSUE TITLE
No sound system

### ISSUE THREAD

**Issue by dadrian** [um-cseg/chez-betty#74]
There is no speaker system in the Chez Betty lounge

**Comment by dadrian** [comment]
I assume this was closed because it was implemented?

**Comment by dadrian** [comment]
@bradjc pls fix

**Comment by bradjc** [comment]
![2016-02-07 13 34 33](https://cloud.githubusercontent.com/assets/1467890/12875399/723e15e6-cdb7-11e5-9024-79b1620b2d49.jpg)
